Spring 08
antoniukivan/jv-cinema-shop pull request #10
Opened 2021-02-22 09:06 UTC by antoniukivan

2021-02-22 09:42 UTC, YuraBondarenko approved these changes

2021-02-22 11:31 UTC, Sofasmile requested changes
good job)

2021-02-22 11:31 UTC, Sofasmile commented on src/main/java/ua/com/cinema/dao/RoleDao.java
> +    Role getRoleByName(String roleName);
```suggestion
    Optional<Role> getRoleByName(String roleName);
```

2021-02-22 11:31 UTC, Sofasmile commented on src/main/java/ua/com/cinema/security/CustomUserDetailsService.java
> +        return builder.build();
```suggestion
            return builder.build();
        }
        throw new UsernameNotFoundException("User not found.");
```

2021-02-22 15:27 UTC, Sofasmile requested changes

2021-02-22 15:27 UTC, Sofasmile commented on src/main/java/ua/com/cinema/security/AuthenticationServiceImpl.java
> +        user.setRoles(Set.of(roleService.getRoleByName("USER").get()));
```suggestion
        user.setRoles(Set.of(roleService.getRoleByName("USER")));
```

2021-02-22 15:27 UTC, Sofasmile commented on src/main/java/ua/com/cinema/service/RoleService.java
> +    Optional<Role> getRoleByName(String roleName);
in this case we should use Optional only on the dao layer

2021-02-23 09:42 UTC, Sofasmile approved these changes

2021-02-25 14:41 UTC, merged