Hb 06
antoniukivan/jv-cinema-shop pull request #4
Opened 2021-02-03 17:12 UTC by antoniukivan

2021-02-03 17:18 UTC, YuraBondarenko approved these changes

2021-02-04 09:28 UTC, dmytro-hryhoruk requested changes

2021-02-04 09:28 UTC, dmytro-hryhoruk commented on src/main/java/ua/com/cinema/dao/impl/ShoppingCartDaoImpl.java
> +                    + "and sc.user.password = :password", ShoppingCart.class);
Do we need all of these joins?

2021-02-04 09:28 UTC, dmytro-hryhoruk commented on src/main/java/ua/com/cinema/dao/impl/ShoppingCartDaoImpl.java
> +                    + "and sc.user.password = :password", ShoppingCart.class);
You can just use the whole user in where statement

2021-02-04 10:30 UTC, dmytro-hryhoruk approved these changes

2021-02-04 13:55 UTC, merged